Precompilation seems to be bothering Cxx :(
OUTPUT:

julia> using Nemo
INFO: Recompiling stale cache file /home/malex/.julia/lib/v0.5/Nemo.ji for module Nemo.
ERROR: LoadError: LoadError: BoundsError: attempt to access 0-element Array{Cxx.ClangCompiler,1}
  at index [1]
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:392
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:392
while loading /home/malex/.julia/v0.5/Cxx/src/std.jl, in expression starting on line 3
while loading /home/malex/.julia/v0.5/Cxx/src/Cxx.jl, in expression starting on line 171
ERROR: LoadError: LoadError: Failed to precompile Cxx to /home/malex/.julia/lib/v0.5/Cxx.ji
 in error at ./error.jl:21
 in require at ./loading.jl:312
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:392
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:392
while loading /home/malex/.julia/v0.5/Nemo/src/singular/SingularTypes.jl, in expression starting on line 11
while loading /home/malex/.julia/v0.5/Nemo/src/Nemo.jl, in expression starting on line 139
ERROR: Failed to precompile Nemo to /home/malex/.julia/lib/v0.5/Nemo.ji
 in error at ./error.jl:21
 in recompile_stale at ./loading.jl:549